CREATE TABLE "SA"."PERFIL"
(
   CORRELATIVO int PRIMARY KEY NOT NULL,
   NOMBRE varchar(50) NOT NULL,
   FECHACREACION date NOT NULL,
   FECHAMODIFICACION date,
   USUARIOCREADOR varchar(10) NOT NULL,
   USUARIOMODIF varchar(10),
   MAQUINACREACION varchar(10) NOT NULL,
   MAQUINAMODIF varchar(10),
   ELIMINADO char(1),
   ROWVERSION int NOT NULL,
   RESTAURADO char(1)
)
;
CREATE UNIQUE INDEX SQL180117151618260 ON "SA"."PERFIL"(CORRELATIVO)
;



CREATE TABLE "SA"."PERFIL_DETALLE"
(
   IDPERFIL int NOT NULL,
   IDPERMISO int NOT NULL,
   FECHACREACION date NOT NULL,
   USUARIOCREADOR varchar(10) NOT NULL,
   MAQUINACREACION varchar(10) NOT NULL,
   CONSTRAINT SQL180117151802380 PRIMARY KEY (IDPERFIL,IDPERMISO)
)
;
CREATE UNIQUE INDEX SQL180117151802380 ON "SA"."PERFIL_DETALLE"
(
  IDPERFIL,
  IDPERMISO
)
;
CREATE TABLE "SA"."PERMISO"
(
   CORRELATIVO int PRIMARY KEY NOT NULL,
   NOMBRESERVICIO varchar(100),
   NOMBREPANTALLA varchar(100),
   FECHACREACION date NOT NULL,
   FECHAMODIFICACION date,
   USUARIOCREADOR varchar(10) NOT NULL,
   USUARIOMODIF varchar(10),
   MAQUINACREACION varchar(10) NOT NULL,
   MAQUINAMODIF varchar(10),
   ELIMINADO char(1),
   ROWVERSION int NOT NULL,
   RESTAURADO char(1),
   ASIGNARTODOS char(1)
)
;
CREATE UNIQUE INDEX SQL180117151210100 ON "SA"."PERMISO"(CORRELATIVO)
;
CREATE TABLE "SA"."PERMISO_DETALLE"
(
   IDPERMISO int NOT NULL,
   METODO varchar(30) NOT NULL,
   FECHACREACION date NOT NULL,
   CONSTRAINT SQL180117151318230 PRIMARY KEY (IDPERMISO,METODO)
)
;
CREATE UNIQUE INDEX SQL180117151318230 ON "SA"."PERMISO_DETALLE"
(
  IDPERMISO,
  METODO
)
;
CREATE TABLE "SA"."ROL"
(
   CORRELATIVO int PRIMARY KEY NOT NULL,
   NOMBRE varchar(50),
   ESTADO char(2),
   FECHACREACION date NOT NULL,
   FECHAMODIFICACION date,
   USUARIOCREADOR varchar(10) NOT NULL,
   USUARIOMODIF varchar(10),
   MAQUINACREACION varchar(10) NOT NULL,
   MAQUINAMODIF varchar(10),
   ELIMINADO char(1),
   ROWVERSION int NOT NULL,
   RESTAURADO char(1)
)
;
CREATE UNIQUE INDEX SQL180117152027870 ON "SA"."ROL"(CORRELATIVO)
;
CREATE TABLE "SA"."ROL_DETALLE"
(
   IDROL int NOT NULL,
   IDPERFIL int NOT NULL,
   FECHACREACION date NOT NULL,
   USUARIOCREADOR varchar(10) NOT NULL,
   MAQUINACREACION varchar(10) NOT NULL,
   CONSTRAINT SQL180118143954710 PRIMARY KEY (IDROL,IDPERFIL)
)
;
CREATE UNIQUE INDEX SQL180118143954710 ON "SA"."ROL_DETALLE"
(
  IDROL,
  IDPERFIL
)
;
CREATE TABLE "SA"."USUARIO_ROL"
(
   IDROL int NOT NULL,
   IDLOGIN int NOT NULL,
   FECHACREACION date NOT NULL,
   USUARIOCREADOR varchar(10) NOT NULL,
   MAQUINACREACION varchar(10) NOT NULL,
   CONSTRAINT SQL180118141709450 PRIMARY KEY (IDROL,IDLOGIN)
)
;
CREATE UNIQUE INDEX SQL180118141709450 ON "SA"."USUARIO_ROL"
(
  IDROL,
  IDLOGIN
)
;

CREATE TABLE "SA"."LOGIN"
(
   CORRELATIVO int PRIMARY KEY NOT NULL,
   LOGIN varchar(100) NOT NULL,
   PASSWORD varchar(200) NOT NULL,
   PASSWORDANTERIOR varchar(200),
   IDPERSONA int NOT NULL,
   FECHACREACION date NOT NULL,
   FECHAMODIFICACION date,
   USUARIOCREADOR varchar(10) NOT NULL,
   USUARIOMODIF varchar(10),
   MAQUINACREACION varchar(10) NOT NULL,
   MAQUINAMODIF varchar(10),
   ELIMINADO char(1),
   ROWVERSION int NOT NULL,
   RESTAURADO char(1),
   HABILITADO char(1)
)
;
CREATE UNIQUE INDEX SQL180117145444240 ON "SA"."LOGIN"(CORRELATIVO)
;

